#include<stdio.h>
#include<stdlib.h>
int main(){
    int **p=(int **)malloc(2*sizeof(int *));
    //p is a pointer to pointer array generated by malloc
    int i,j;
    for(i=0;i<2;i++){
        *(p+i)=(int *)calloc(4,sizeof(int)); //array of 4 integers generated by calloc
    }
    for(i=0;i<2;i++){
        for(j=0;j<4;j++){
            p[i][j]=i+j;
        }
        printf("\n");
    }
    printf("p=%d\n",p);
    printf("*(p+0)=%d\n",*(p+0));
    printf("*(p+1)=%d\n",*(p+1));
    for(i=0;i<2;i++){
        for(j=0;j<4;j++){
            printf("%d ",*(*(p+i)+j));
        }
        printf("\n");
    }
    free(p);
    return 0;
}
